version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3.9.11-management-alpine
    container_name: study-rabbitmq
    hostname: queue
    volumes:
      - .data/rabbitmq:/var/lib/rabbitmq/mnesia
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      - RABBITMQ_DEFAULT_USER=study
      - RABBITMQ_DEFAULT_PASS=study